name = "Fig"
grammar = "fig"
path_suffixes = ["figl"]
line_comments = ["# "]
autoclose_before = ",]}"
brackets = [
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
]
