// Build the fig WebAssembly module and inline it into the TypeScript source.
//
// Runs `zig build wasm` at the repository root, then base64-encodes the
// resulting freestanding reactor module into `src/wasm-bytes.ts`. Inlining
// (rather than shipping a separate `.wasm`) keeps the published package a single
// JS payload that loads identically under Node and every bundler, with no
// `fetch`/`fs` path to special-case. The module imports nothing, so it
// instantiates synchronously.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..", "..");
const srcDir = resolve(here, "..", "src");

// No format is compiled into the published module. Each is a JavaScript
// language the caller imports and registers (`@diaryx/fig/languages/<name>`),
// standing in for the compiled format at its own `Format` number — so a page
// pays for the formats it uses and no others, and the module itself is the
// core alone: the tree, the editor's splice engine, serialization, embeds.
//
// FIG_WASM_LANGUAGES names formats to compile in anyway, comma-separated, or
// `all` for every one: a reference module whose compiled formats the
// languages are held to (`scripts/record-printed.mjs`). A language registered
// into such a module under a compiled format's name is refused as taken.
const LANGUAGES = ["json", "yaml", "toml", "zon", "fig", "ini", "dotenv", "properties", "plist", "nestedtext"];
const wanted = (process.env.FIG_WASM_LANGUAGES ?? "").split(",").map((s) => s.trim()).filter(Boolean);
for (const w of wanted) {
  if (w !== "all" && !LANGUAGES.includes(w)) throw new Error(`FIG_WASM_LANGUAGES: no format named \`${w}\` (one of ${LANGUAGES.join(", ")}, or all)`);
}
const on = (name) => wanted.includes("all") || wanted.includes(name);
const zigArgs = ["build", "wasm", ...LANGUAGES.map((name) => `-D${name}=${on(name)}`)];

console.error(`· zig ${zigArgs.join(" ")}`);
execFileSync("zig", zigArgs, { cwd: repoRoot, stdio: "inherit" });

const wasmPath = join(repoRoot, "zig-out", "bin", "fig.wasm");
const wasm = readFileSync(wasmPath);
const base64 = wasm.toString("base64");
console.error(`· fig.wasm ${(wasm.length / 1024).toFixed(1)} KiB → ${(base64.length / 1024).toFixed(1)} KiB base64`);

const banner = `// @generated by scripts/build-wasm.mjs — do not edit by hand.
// The fig core (src/c_api.zig) compiled to a freestanding wasm32 reactor
// module, base64-encoded. Regenerate with \`npm run build:wasm\`.
`;

// Chunk the literal so editors/diff tools don't choke on one multi-hundred-KiB
// line, and emit it as an ARRAY joined at runtime rather than a `"a" + "b" + …`
// expression: a deep `+`-chain is parsed by recursive descent, so a large module
// overflows the stack of Node's lightweight TS type-stripper (and some bundlers).
// An array literal parses flat.
const chunks = [];
for (let i = 0; i < base64.length; i += 120) chunks.push(base64.slice(i, i + 120));
const literal = chunks.map((c) => `  "${c}",`).join("\n");

mkdirSync(srcDir, { recursive: true });
writeFileSync(
  join(srcDir, "wasm-bytes.ts"),
  `${banner}export const WASM_BASE64: string = [\n${literal}\n].join("");\n`,
);
console.error("· wrote src/wasm-bytes.ts");
