#!/bin/sh
# Build the `fig` CLI with a Zig that has no build system.
#
# For a Zig compiled to wasm32-wasi, where `build` is compiled out of the
# compiler and WASI preview 1 could not spawn a build runner anyway. Run this
# from the root of the fig source tree; see docs/wasi-build.md.
#
#   ZIG       compiler to invoke        (default: zig)
#   OUT       output module name        (default: fig.wasm)
#   OPTIMIZE  optimize flag
#
# Any extra arguments are passed through to `zig build-exe`, which is how you
# supply -fno-compiler-rt and a prebuilt libcompiler_rt.a outside Wish.
set -eu

ZIG=${ZIG:-zig}
OUT=${OUT:-fig.wasm}
OPTIMIZE=${OPTIMIZE:--Doptimize=ReleaseSmall}

if [ ! -f src/cli/main.zig ]; then
    echo "wasi-build: run this from the root of the fig source tree" >&2
    exit 1
fi

if [ ! -f build_options.zig ]; then
    echo "wasi-build: build_options.zig is missing." >&2
    echo >&2
    echo "It is generated by \`zig build\`, which is the one thing unavailable here." >&2
    echo "Get it one of two ways:" >&2
    echo "  * download build_options.zig from the fig release you are building, or" >&2
    echo "  * on a machine with a full Zig, run \`zig build wasi-options\` in this" >&2
    echo "    tree and copy zig-out/build_options.zig next to src/." >&2
    exit 1
fi

# Three modules: root (the CLI) depends on fig (the library) and build_options;
# fig depends on build_options. Each --dep applies to the -M that follow
"$ZIG" build-exe \
    --dep fig --dep build_options -Mroot=src/cli/main.zig \
    --dep build_options -Mfig=src/root.zig \
    -Mbuild_options=build_options.zig \
    -target wasm32-wasi "$OPTIMIZE" --name "${OUT%.wasm}" \
    "$@"